WSLg: Include missing array header (#850)
This fixes the following error with gcc:

main.cpp: In function 'std::string TranslateWindowsPath(const char*)':
main.cpp:80:27: error: aggregate 'std::array<char, 128> buffer' has incomplete type and cannot be defined
   80 |     std::array<char, 128> buffer;
      |                           ^~~~~~

std::array was added in 321cf1bcd4fd99112a0cde933816b0d9a4121e6b commit